### ISSUE TITLE
.zip file improvements

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/SkeletonComparativeEffectStudy#29]
see forum post with errors here
https://forums.ohdsi.org/t/import-zip-file-into-r-method/9533/3

**Comment by schuemie** [comment]
Hi @vojtechhuser

The only error message I see in your post is "Requested stratified analysis, but no stratumId column found in population. Please use matchOnPs or stratifyByPs to create strata." This is odd, because the relevant analysis (analysis 2)  in ATLAS does use matching. I downloaded and ran the study package myself, and saw no such error message. Was the analysis in ATLAS changed after you ran it?
